"""Offline, fixture-only packing drawer presentation for Phase D.

This renderer has no persistence, source access, network requests, or operational
mutation path. Its controls demonstrate only local validation and keyboard flow.
"""


def packing_drawer_html() -> str:
    """Return one static reconciliation drawer backed solely by fixed fixture evidence."""
    return """<button id="open-packing-drawer" class="secondary" type="button">Open packing drawer</button>
<aside id="packing-drawer" class="modal" role="dialog" aria-modal="true" aria-labelledby="packing-drawer-title" hidden>
  <section class="dialog packing-dialog" data-plan-provenance="fixture-provenance-2026-08-30">
    <div class="toolbar"><div><h2 id="packing-drawer-title">Packing reconciliation</h2><p class="meta">OPEN · fixture plan · provenance pinned: fixture-provenance-2026-08-30</p></div><button id="close-packing-drawer" class="secondary" type="button">Close drawer</button></div>
    <p class="authority">CORE-LOCAL FIXTURE VIEW · NO SOURCE AUTHORITY CHANGED</p>
    <section aria-labelledby="packing-line-title"><h3 id="packing-line-title">Source line identity</h3><p id="packing-selected-line" class="meta">Captured source order · ORD//2026/001 · line 0007 · SubCust A1</p><div id="packing-line-list" class="packing-lines" role="listbox" aria-label="Fixture packing source lines"><button type="button" class="result" role="option" aria-selected="true" data-line="ORD//2026/001 · line 0007 · SubCust A1" data-english="Anubias barteri" data-thai="อนูเบียสบาร์เทอรี">ORD//2026/001 · line 0007 · SubCust A1 · Anubias barteri</button><button type="button" class="result" role="option" aria-selected="false" data-line="ORD//2026/001 · line 0008 · SubCust A1" data-english="Bucephalandra fixture" data-thai="บูเซฟาแลนด์รา">ORD//2026/001 · line 0008 · SubCust A1 · Bucephalandra fixture</button></div></section>
    <section aria-label="Quantity reconciliation"><h3>Quantity reconciliation</h3><table><thead><tr><th>Source line</th><th>Allocated</th><th>Unavailable</th><th>Remaining</th></tr></thead><tbody><tr><td>ORD//2026/001 · line 0007 · SubCust A1</td><td>4</td><td>2</td><td>4</td></tr><tr><td>ORD//2026/001 · line 0008 · SubCust A1</td><td>0</td><td>0</td><td>6</td></tr></tbody></table><p class="meta">Unavailable stays under its captured SubCust chapter and retains the original source identity.</p></section>
    <section aria-label="Fixture allocation review"><h3>Fixture allocation review</h3><label>Target box <select id="packing-box-target"><option value="">Choose a box</option><option value="1">Box 1</option><option value="2">Box 2</option></select></label><label>Quantity <input id="packing-quantity" inputmode="decimal" aria-describedby="packing-validation"></label><button id="packing-review-allocation" class="open" type="button">Review allocation</button><p id="packing-validation" class="meta" aria-live="polite">Choose a source line, target box, and positive quantity.</p></section>
    <section aria-labelledby="packing-history-title"><h3 id="packing-history-title">Correction history</h3><ol><li>Fixture reversal retained: prior box allocation was reversed with reason “fixture correction”.</li></ol></section>
  </section>
</aside>
<script>(()=>{const drawer=document.querySelector('#packing-drawer'),openButton=document.querySelector('#open-packing-drawer'),closeButton=document.querySelector('#close-packing-drawer'),lineList=document.querySelector('#packing-line-list'),selectedLine=document.querySelector('#packing-selected-line'),boxTarget=document.querySelector('#packing-box-target'),quantity=document.querySelector('#packing-quantity'),reviewButton=document.querySelector('#packing-review-allocation'),validation=document.querySelector('#packing-validation');let invoker=openButton,currentLanguage='english';function setSelected(button){for(const row of lineList.querySelectorAll('[role="option"]'))row.setAttribute('aria-selected',String(row===button));selectedLine.textContent='Captured source order · '+button.dataset.line+' · '+(currentLanguage==='english'?button.dataset.english:button.dataset.thai)}function toggleLanguage(){currentLanguage=currentLanguage==='english'?'thai':'english';const selected=lineList.querySelector('[aria-selected="true"]');if(selected)setSelected(selected)}function open(){invoker=document.activeElement;drawer.hidden=false;closeButton.focus()}function close(){drawer.hidden=true;invoker.focus()}openButton.addEventListener('click',open);closeButton.addEventListener('click',close);lineList.addEventListener('click',event=>{const button=event.target.closest('[role="option"]');if(button)setSelected(button)});lineList.addEventListener('keydown',event=>{const button=event.target.closest('[role="option"]');if(event.key===' '&&button){event.preventDefault();document.body.dataset.scrollLocked='true';toggleLanguage();return}if(event.key==='Enter'&&button){event.preventDefault();setSelected(button)}});boxTarget.addEventListener('change',()=>{validation.textContent=boxTarget.value?'Choose a positive quantity.':'Select a target box.'});reviewButton.addEventListener('click',()=>{if(!(Number(quantity.value)>0)){validation.textContent='Enter a positive quantity.';quantity.focus();return}if(!boxTarget.value){validation.textContent='Select a target box.';boxTarget.focus();return}validation.textContent='Ready for fixture review only; no allocation was recorded.'});drawer.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close()}})})();</script>"""
